FROM node:18-slim

# RUN apt-get update
# RUN apt-get install python3 make gcc g++ -y
RUN npm install -g npm

ARG MODULE=workers

# assumes we're in <project>/. directory
COPY ${MODULE}/. /app

WORKDIR /app

RUN rm -rf node_modules
RUN npm install
