version: '3'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4001:4001
      - 3000:3000  # Dashboard app, if created
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      # - CUBEJS_DATASOURCES=default,indexDb
      # - CUBEJS_DB_HOST=host.docker.internal
      # - CUBEJS_DB_PORT=5432
      # - CUBEJS_DB_NAME=subledgr_dev
      # - CUBEJS_DB_USER=subledgr_dev
      # - CUBEJS_DB_PASS=subledgr_dev
      # - CUBEJS_DB_TYPE=mysql
      # - CUBEJS_DB_INDEXDB_HOST=192.168.1.92
      # - CUBEJS_DB_INDEXDB_PORT=9432
      # - CUBEJS_DB_INDEXDB_NAME=polkastore
      # - CUBEJS_DB_INDEXDB_USER=postgres
      # - CUBEJS_DB_INDEXDB_PASS=hydra
      # - CUBEJS_DB_INDEXDB_TYPE=postgres

    volumes:
      - ./conf:/cube/conf