import { QUERY_ASSET } from './assets.gql'
import { QUERY_CURRENCIES } from "./currencies.gql";
import { QUERY_PORTFOLIO_VIEW, QUERY_PORTFOLIO_WALLETS } from "./portfolios.gql";
import { QUERY_PRICES, QUERY_PRICE_HISTORY } from "./prices.gql";
import { QUERY_TRANSACTIONS } from "./transactions.gql";
import { QUERY_WALLETS, QUERY_WALLET, QUERY_WALLET_DETAILS, QUERY_WALLET_BALANCE, QUERY_WALLET_TRANSACTIONS, QUERY_WALLET_VALUE_HISTORY } from "./wallets.gql";

export {
  QUERY_ASSET,
  QUERY_CURRENCIES,
  QUERY_PORTFOLIO_WALLETS,
  QUERY_PORTFOLIO_VIEW,
  QUERY_PRICES,
  QUERY_PRICE_HISTORY,
  QUERY_TRANSACTIONS,
  QUERY_WALLETS,
  QUERY_WALLET,
  QUERY_WALLET_BALANCE,
  QUERY_WALLET_DETAILS,
  QUERY_WALLET_TRANSACTIONS,
  QUERY_WALLET_VALUE_HISTORY,
}
