import { QUERY_ASSET } from './assets.gql'
import { QUERY_CURRENCIES } from "./currencies.gql";
import { QUERY_PORTFOLIO_VIEW, QUERY_PORTFOLIO_ACCOUNTS,
      MUT_PORTFOLIO_ADD, MUT_PORTFOLIO_EDIT, MUT_PORTFOLIO_DELETE } from "./portfolios.gql";
import { QUERY_PRICE, QUERY_PRICES, QUERY_PRICE_HISTORY } from "./prices.gql";
import { QUERY_TRANSACTIONS } from "./transactions.gql";
import { QUERY_ACCOUNTS_SELECT, QUERY_ACCOUNTS, QUERY_ACCOUNT, QUERY_ACCOUNT_DETAILS,
  QUERY_ACCOUNT_BALANCE1,
  QUERY_ACCOUNT_BALANCE,
  QUERY_ACCOUNT_PORTFOLIOS,
  QUERY_ACCOUNT_TRANSACTIONS,
  QUERY_ACCOUNT_VALUE_HISTORY } from "./accounts.gql";

export {
  QUERY_ACCOUNTS_SELECT,
  QUERY_ACCOUNTS,
  QUERY_ACCOUNT,
  QUERY_ACCOUNT_BALANCE1,
  QUERY_ACCOUNT_BALANCE,
  QUERY_ACCOUNT_DETAILS,
  QUERY_ACCOUNT_PORTFOLIOS,
  QUERY_ACCOUNT_TRANSACTIONS,
  QUERY_ACCOUNT_VALUE_HISTORY,
  QUERY_ASSET,
  QUERY_CURRENCIES,
  QUERY_PORTFOLIO_ACCOUNTS,
  QUERY_PORTFOLIO_VIEW,
  MUT_PORTFOLIO_ADD,
  MUT_PORTFOLIO_EDIT,
  MUT_PORTFOLIO_DELETE,
  QUERY_PRICE,
  QUERY_PRICES,
  QUERY_PRICE_HISTORY,
  QUERY_TRANSACTIONS,
}
